SCREEN_WIDTH = 800
SCREEN_HEIGHT = 600
SCREEN_SIZE = (SCREEN_WIDTH, SCREEN_HEIGHT)

BORDER_SIZE = 0

PUZZLE_WIDTH = (SCREEN_WIDTH - 2 * BORDER_SIZE)
PUZZLE_HEIGHT = (SCREEN_HEIGHT - 2 * BORDER_SIZE)
PUZZLE_SIZE = (PUZZLE_WIDTH, PUZZLE_HEIGHT)

MIN_PIECE_SIZE = 30

MAX_PIECES_WIDTH = (SCREEN_WIDTH - 2 * BORDER_SIZE) // MIN_PIECE_SIZE
MAX_PIECES_HEIGHT = (SCREEN_HEIGHT - 2 * BORDER_SIZE) // MIN_PIECE_SIZE

WHITE = (255, 255, 255)
BLACK = (0, 0, 0)
SHADOW_COLOR = (0, 0, 0, 60)

EPS = 20
